[files]
extend-exclude = [
  "docs/project/archive/**",
]

[default.extend-words]
AREDN = "AREDN"
BPSec = "BPSec"
BPv7 = "BPv7"
Harriet = "Harriet"
labgrid = "labgrid"
LibreMesh = "LibreMesh"
LXMF = "LXMF"
Meshtastic = "Meshtastic"
OpenWrt = "OpenWrt"
RNode = "RNode"
Reticulum = "Reticulum"
Zack = "Zack"
